[package]
name = "chirp"
version = "0.1.0"
authors = ["Roland Mueller"]
edition = "2018"

[dependencies]
embedded-hal = "0.2.2"

[dev-dependencies]
microbit = "0.7.0"
panic-halt = "0.2.0"
cortex-m = "0.5.8"
cortex-m-rt = "0.6.7"